### ISSUE TITLE
Auto-close issue tracker tickets when an error is resolved

### ISSUE THREAD

**Issue by ndbroadbent** [errbit/errbit#371]
Clicking 'resolve' should automatically close the ticket in the issue tracker.

**Comment by tjnet** [comment]
I want to contribute this issue :smiley_cat:

**Comment by stevecrozz** [comment]
@tjnet Cool. To get this working, there will need to be three changes in three projects:

- [ ] We'll need a new interface in errbit_plugin, maybe a close_issue method here: https://github.com/errbit/errbit_plugin
- [ ] Then we'll need to implement close_issue in https://github.com/errbit/errbit_github_plugin
- [ ] And finally, we'll need to call the method if it has been implemented in the resolve issue action.

**Comment by tjnet** [comment]
thank you for your explanation. I'll try! :smiley:

**Comment by tjnet** [comment]
as a preparation for this issue, I wrote the basic test for https://github.com/errbit/errbit_github_plugin in this [Pull Request](https://github.com/errbit/errbit_github_plugin/pull/6).

**Comment by stevecrozz** [comment]
I don't agree with the original issue description, and in fact I'm starting to think the whole concept of 'resolving' an issue is unnecessary inside errbit. We do now offer a button to close a linked issue from errbit to complement the create action, but I don't see the need for errbit errors to have their own state concept. It seems natural to manage the state of an issue in an issue tracker.
